application: womerton-farm
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:

# Temporary for testing
- url: /index.html
  static_files: index.html
  upload: index.html

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt 
  
# Fonts
- url: /fonts/(.*) 
  static_files: static/fonts/\1 
  upload: static/fonts/(.*) 
  
# Icons
- url: /favicon.ico
  static_files: static/ico/favicon.ico
  upload: static/ico/favicon.ico 

- url: /ico/(.*) 
  static_files: static/ico/\1 
  upload: static/ico/(.*) 

# Images
- url: /images/(.*) 
  static_files: static/img/\1 
  upload: static/img/(.*) 

# JavaScript
- url: /js/(.*) 
  static_files: static/js/\1 
  upload: static/js/(.*) 
  
# Style Sheets
- url: /css/(.*) 
  static_files: static/css/\1 
  upload: static/css/(.*) 


- url: .*
  script: main.wsgi_app
  
